import type { GreetingLibrary } from './types';

// Short, local-only lines. Keep each period distinct so the clock feels noticed.
export const englishGreetings: GreetingLibrary = {
  earlyMorning: [
    "You're up early 👀", 'First thought of the day?', 'Morning, early bird.', 'Already thinking?',
    'Got an early idea?', 'Before the day gets loud.', 'The quiet hours suit ideas.', 'Up before your to-do list?',
    'Something on your mind already?', 'Morning brain activated.', 'Catch that first thought.', 'A little head start?',
    'The day can wait a minute.', 'What woke your brain up?', 'One thought before breakfast?', 'Fresh morning, fresh page.',
    'A thought before sunrise?', 'Your ideas got up first.', 'Early notes count, too.', 'What is brewing this early?',
    'Good time to jot it down.', 'The quiet makes room.', 'Is that an early spark?', 'Start with one small thought.',
    'A note before the rush?', 'Let the morning unfold.', 'Your first chit is ready.', 'Anything to carry into today?',
    'A clear head, maybe?', 'Before the inbox wakes up.', 'This thought came early.', 'Up with an idea?',
    'The morning is yours.', 'What is on your mind?', 'Save it before the day starts.',
  ],
  morning: [
    'Good morning! ☀️', "Morning! What's on your mind?", 'New day, new thoughts.', 'Got something to jot down?',
    'Morning brain dump?', "What's today's first thought?", 'Ready when you are.', "Let's catch those ideas.",
    'Anything worth remembering?', 'Start with a quick chit.', "What's brewing?", 'Got a thought already?',
    'Morning idea?', "Don't lose that thought.", 'What are we thinking today?', 'A fresh page for today.',
    'Did something just click?', 'Keep that idea close.', 'A note for later?', 'One thought at a time.',
    'What should future you know?', 'Good time for a quick note.', 'Something to save this morning?',
    'Just chit it down.', 'Chat now. Sort later.', 'Start anywhere.', 'A tiny thought can stay.',
    'Your board can wait.', 'Capture first, sort later.', 'The day starts here.', 'Any ideas over coffee?',
    'What is worth keeping?', 'A thought before the rush?', 'One quick note?', 'Tell me the short version.',
    'No need to organize yet.', 'Keep this morning thought.', 'Ideas welcome, big or small.', 'Write first. Decide later.',
    'A good thought deserves a home.', 'Your morning brain called.', 'Ready for a brain dump?', 'Put that thought somewhere safe.',
  ],
  afternoon: [
    'Good afternoon!', 'Quick thought?', 'Got something on your mind?', "Don't lose that idea.",
    'Drop it here.', 'Thought worth keeping?', 'Midday brain dump?', 'Something to remember later?',
    "I'm listening.", 'Write it before it disappears.', 'Random afternoon thought?', 'Got something for later?',
    'Save that idea.', 'Something just crossed your mind?', 'One quick chit?', 'A thought between things?',
    'Pause and put it here.', 'What popped into your head?', 'Keep that little spark.', 'An idea worth a note?',
    'The afternoon has ideas.', 'Make room for that thought.', 'Save now, sort later.', 'A quick note can help.',
    'Thought first. Board later.', 'Anything you want to keep?', 'A little mental offload?', 'Drop a thought, carry on.',
    'Still on your mind?', 'One thing before you forget?', 'What should wait here?', 'Your thought can land here.',
    'Something worth coming back to?', 'Let me hold that idea.', 'Did an idea sneak in?', 'Keep the good bits.',
    'Catch it while it is fresh.', 'A note for the afternoon?', 'Just get it out.', 'Something clicked just now?',
    'Leave this for later you.', 'A thought in passing?', 'Give that idea a spot.',
  ],
  evening: [
    'Good evening!', 'Long day?', 'Anything you want to remember?', 'Evening thoughts?',
    'Got something from today?', 'Save it before you forget.', "What's still on your mind?", "Drop today's thoughts here.",
    'Something worth keeping?', "How'd your day go?", 'One last idea from today?', 'Something to carry forward?',
    'Evening brain dump?', 'Keep that thought.', 'What stayed with you today?', 'A little end-of-day note?',
    'Anything to leave here?', 'That thought can rest here.', 'Before the day slips away.', 'What should tomorrow remember?',
    'An idea from the day?', 'A note before winding down?', 'Put the day into words.', 'Still thinking about something?',
    'Keep the useful bits.', 'One thing to remember?', 'The day had a point.', 'Write it, then unwind.',
    'A thought to save for tomorrow?', 'Let that idea land.', 'What was worth noticing?', 'A little recap, maybe?',
    'Drop it here for later.', 'The quiet is back.', 'Your board can wait till tomorrow.', 'Capture it before dinner?',
    'Anything left on your mind?', 'One more note for today?',
  ],
  night: [
    'Late-night thought? 👀', 'Still thinking?', 'Before you forget…', 'Night brain is active again?',
    'One last thought?', 'Got something keeping you awake?', 'Write it down for tomorrow.', 'Random late-night thought?',
    'Brain still working?', 'Leave it here for tomorrow.', 'Something you just remembered?', 'Last-minute idea?',
    'One more chit?', 'Night thoughts again?', 'Save it before sleep.', 'Your brain had one more thing?',
    'Put it somewhere safe.', 'A thought before lights out?', 'No need to remember it all.', 'Let me keep that thought.',
    'The idea can sleep here.', 'An after-hours spark?', 'What is lingering tonight?', 'A note for morning you?',
    'Catch it, then rest.', 'Thoughts can wait here.', 'Still one thing on your mind?', 'Write it, then let go.',
    'A quiet little note?', 'One thing to leave behind?', 'The night has ideas, too.', 'Save the thought, skip the sorting.',
    'A reminder for daylight?', 'Nighttime brain dump?', 'Put that thought to bed.', 'Something worth keeping overnight?',
    'Is that a bedtime idea?', 'A late note for later?',
  ],
  lateNight: [
    "You're still awake? 👀", 'Midnight idea?', "Your brain won't clock out, huh?", 'Something keeping you up?',
    "Don't trust tomorrow to remember.", '2 AM thoughts hit different.', 'Put it here before sleep wins.',
    "Okay… what's the thought?", 'Brain said one more thing?', "I'll keep it safe until morning.",
    'Sleep can wait for one thought.', 'Another midnight idea?', "That thought couldn't wait?", 'Okay, tell me.',
    'One last thing before bed?', 'The brain has odd hours.', 'A tiny thought at this hour?',
    'Give that idea a landing spot.', 'Your pillow deserves a break.', 'A note for tomorrow you?',
    'The midnight shift is here.', 'Still collecting thoughts?', 'Let this one rest here.',
    'An idea after everyone slept?', 'No need to hold it all night.', 'Catch it, then catch some sleep.',
    'A sleepy little brain dump?', 'The thought can stay awake here.', 'What is your brain plotting?',
    'A quick chit before sleep?', 'Is this the last one?', 'Your idea missed bedtime.',
    'Leave it here till morning.', 'Thoughts after dark, huh?', 'Write it down. Eyes closed next.',
  ],
};
