import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { router } from 'expo-router';
import { useBottomTabBarHeight } from 'expo-router/tabs';
import { useSQLiteContext } from 'expo-sqlite';
import { AppHeader, EmptyState, IconButton, Screen } from '@/components/ui/primitives';
import { ChitsLoader, useChitsLoading } from '@/components/ui/chits-loader';
import { useAppDrawer } from '@/components/navigation/app-drawer';
import { useTheme } from '@/components/theme-provider';
import { spacing } from '@/constants/theme';
import { createBoardRepository } from '@/db/repositories';
type Result = { id: string; title: string; context: string; kind: 'message' | 'card' | 'board' | 'file' };
export default function SearchScreen() { const database = useSQLiteContext(); const { openDrawer } = useAppDrawer(); const { tokens: theme } = useTheme(); const tabBarHeight = useBottomTabBarHeight(); const repository = useMemo(() => createBoardRepository(database), [database]); const [term, setTerm] = useState(''); const [archived, setArchived] = useState(false); const [results, setResults] = useState<Result[]>([]); const [searching, setSearching] = useState(false); const showSearchLoader = useChitsLoading(searching); const timer = useRef<ReturnType<typeof setTimeout> | null>(null); const search = useCallback(async (value: string, showArchived = archived) => { const trimmed = value.trim(); if (!trimmed) { setResults([]); setSearching(false); return; } setSearching(true); try { setResults(await repository.search(trimmed, showArchived)); } finally { setSearching(false); } }, [archived, repository]); const queueSearch = useCallback((value: string) => { if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => { void search(value); }, 220); }, [search]); useEffect(() => () => { if (timer.current) clearTimeout(timer.current); }, []); const open = (result: Result) => router.push(result.kind === 'board' ? `/board/${result.id}` : result.kind === 'card' ? `/card/${result.id}` : result.kind === 'message' || result.kind === 'file' ? `/chat?messageId=${result.id}` : '/search'); return <Screen edges={['top', 'left', 'right']}><AppHeader title="Search" leading={<IconButton label="Open navigation" onPress={openDrawer}><Ionicons accessible={false} name="reorder-two-outline" size={24} color={theme.textPrimary} /></IconButton>} /><TextInput value={term} onChangeText={(value) => { setTerm(value); queueSearch(value); }} placeholder="Search your thoughts" placeholderTextColor={theme.textMuted} style={[styles.input, { borderColor: theme.borderSubtle, color: theme.textPrimary, backgroundColor: theme.background }]} /><Pressable onPress={() => { const next = !archived; setArchived(next); void search(term, next); }} style={[styles.filter, { backgroundColor: theme.surfaceElevated }]}><Text style={[styles.filterText, { color: theme.textSecondary }]}>{archived ? 'Including archived' : 'Active items'}</Text></Pressable>{term ? (showSearchLoader ? <ChitsLoader /> : <ScrollView contentContainerStyle={[styles.list, { paddingBottom: tabBarHeight + spacing.md }]}>{results.length ? results.map((result) => <Pressable key={`${result.kind}-${result.id}`} onPress={() => open(result)} style={[styles.result, { borderBottomColor: theme.borderSubtle }]}><Text style={[styles.title, { color: theme.textPrimary }]}>{result.title}</Text><Text style={[styles.context, { color: theme.textSecondary }]}>{result.context}</Text></Pressable>) : <EmptyState title="No matches" description="Try a different word or include archived items." />}</ScrollView>) : <EmptyState title="Find anything later" description="Search messages, cards, boards, and attachment names." />}</Screen>; }
const styles = StyleSheet.create({ input: { minHeight: 46, margin: spacing.md, marginBottom: spacing.xs, paddingHorizontal: spacing.sm, borderRadius: 10, borderWidth: 1 }, filter: { alignSelf: 'flex-start', minHeight: 34, justifyContent: 'center', marginLeft: spacing.md, paddingHorizontal: spacing.sm, borderRadius: 16 }, filterText: { fontSize: 13, fontWeight: '600' }, list: { padding: spacing.md, gap: spacing.xs, flexGrow: 1 }, result: { paddingVertical: spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth }, title: { fontSize: 16 }, context: { fontSize: 13, marginTop: 3 } });
