import type { PropsWithChildren, ReactNode } from 'react';
import { Pressable, StyleSheet, Text, View, type StyleProp, type ViewStyle } from 'react-native';
import { SafeAreaView, type Edge } from 'react-native-safe-area-context';
import { useTheme } from '@/components/theme-provider';
import { layout, spacing, tokens } from '@/constants/theme';
import { ChitsLoader } from './chits-loader';

export function Screen({ children, style, edges }: PropsWithChildren<{ style?: StyleProp<ViewStyle>; edges?: Edge[] }>) { const { tokens: theme } = useTheme(); return <SafeAreaView edges={edges} style={[styles.screen, { backgroundColor: theme.background }, style]}>{children}</SafeAreaView>; }
export const AppScreen = Screen;
export function AppHeader({ title, subtitle, leading, trailing }: { title: string; subtitle?: string; leading?: ReactNode; trailing?: ReactNode }) { const { tokens: theme } = useTheme(); return <View style={[styles.header, { borderBottomColor: theme.borderSubtle }]}><View style={styles.headerSide}>{leading}</View><View style={styles.headerCopy}><Text accessibilityRole="header" accessibilityLabel={title} numberOfLines={1} ellipsizeMode="tail" style={[styles.headerTitle, { color: theme.textPrimary }]}>{title}</Text>{subtitle ? <Text accessibilityLabel={subtitle} style={[styles.headerSubtitle, { color: theme.textMuted }]}>{subtitle}</Text> : null}</View><View style={[styles.headerSide, styles.headerSideTrailing]}>{trailing}</View></View>; }
export function BackHeader({ title, onBack, trailing }: { title: string; onBack: () => void; trailing?: ReactNode }) { const { tokens: theme } = useTheme(); return <AppHeader title={title} leading={<IconButton label="Go back" onPress={onBack}><Text style={[styles.backIcon, { color: theme.textPrimary }]}>‹</Text></IconButton>} trailing={trailing} />; }
export function IconButton({ label, children, onPress, disabled = false }: PropsWithChildren<{ label: string; onPress?: () => void; disabled?: boolean }>) { return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} hitSlop={8} onPress={onPress} style={({ pressed }) => [styles.iconButton, pressed && !disabled && styles.pressed, disabled && styles.disabled]}>{children}</Pressable>; }
export function Divider() { const { tokens: theme } = useTheme(); return <View style={[styles.divider, { backgroundColor: theme.borderSubtle }]} />; }
export function EmptyState({ title, description }: { title: string; description: string }) { const { tokens: theme } = useTheme(); return <View style={styles.emptyState}><Text style={[styles.emptyTitle, { color: theme.textPrimary }]}>{title}</Text><Text style={[styles.emptyDescription, { color: theme.textSecondary }]}>{description}</Text></View>; }
export function LoadingState({ label = 'Preparing Chits…' }: { label?: string }) { return <SafeAreaView style={[styles.screen, styles.loadingScreen, { backgroundColor: tokens.background }]}><ChitsLoader size="large" label={label} /></SafeAreaView>; }
export function FloatingSurface({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { const { tokens: theme } = useTheme(); return <View style={[styles.floatingSurface, { backgroundColor: theme.surface, borderColor: theme.borderSubtle }, style]}>{children}</View>; }
export function BottomSheetSurface({ children, style }: PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { const { tokens: theme } = useTheme(); return <View style={[styles.bottomSheetSurface, { backgroundColor: theme.surface, borderColor: theme.borderSubtle }, style]}>{children}</View>; }
export function PrimaryButton({ label, onPress, disabled = false }: { label: string; onPress: () => void; disabled?: boolean }) { const { tokens: theme } = useTheme(); return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.primaryButton, { backgroundColor: theme.accent }, disabled && styles.disabled]}><Text style={[styles.primaryButtonText, { color: theme.accentText }]}>{label}</Text></Pressable>; }
export function SecondaryButton({ label, onPress, disabled = false }: { label: string; onPress: () => void; disabled?: boolean }) { const { tokens: theme } = useTheme(); return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.secondaryButton, { backgroundColor: theme.surfaceElevated }, disabled && styles.disabled]}><Text style={[styles.secondaryButtonText, { color: theme.textPrimary }]}>{label}</Text></Pressable>; }
export function DestructiveAction({ label, onPress }: { label: string; onPress: () => void }) { const { tokens: theme } = useTheme(); return <Pressable accessibilityRole="button" onPress={onPress} style={styles.destructiveAction}><Text style={[styles.destructiveText, { color: theme.danger }]}>{label}</Text></Pressable>; }
export function SectionHeader({ title }: { title: string }) { const { tokens: theme } = useTheme(); return <Text accessibilityRole="header" style={[styles.sectionHeader, { color: theme.textMuted }]}>{title}</Text>; }
export function ListRow({ title, detail, onPress, trailing }: { title: string; detail?: string; onPress?: () => void; trailing?: ReactNode }) { const { tokens: theme } = useTheme(); return <Pressable accessibilityRole={onPress ? 'button' : undefined} disabled={!onPress} onPress={onPress} style={[styles.listRow, { borderBottomColor: theme.borderSubtle }]}><View style={styles.listCopy}><Text style={[styles.listTitle, { color: theme.textPrimary }]}>{title}</Text>{detail ? <Text style={[styles.listDetail, { color: theme.textSecondary }]}>{detail}</Text> : null}</View>{trailing}</Pressable>; }
export function Toast({ message }: { message: string | null }) { const { tokens: theme } = useTheme(); if (!message) return null; return <View pointerEvents="none" accessibilityLiveRegion="polite" style={styles.toastWrap}><View style={[styles.toast, { backgroundColor: theme.textPrimary }]}><Text style={[styles.toastText, { color: theme.background }]}>{message}</Text></View></View>; }

const styles = StyleSheet.create({
  screen: { flex: 1 }, header: { minHeight: 52, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth }, headerSide: { width: layout.minimumTouchTarget, alignItems: 'flex-start', justifyContent: 'center' }, headerSideTrailing: { alignItems: 'flex-end' }, headerCopy: { flex: 1, minWidth: 0, alignItems: 'center' }, headerTitle: { width: '100%', flexShrink: 1, fontSize: 17, fontWeight: '600', textAlign: 'center' }, headerSubtitle: { fontSize: 11, marginTop: 1 }, backIcon: { fontSize: 30, lineHeight: 30 }, iconButton: { width: layout.minimumTouchTarget, height: layout.minimumTouchTarget, borderRadius: 22, alignItems: 'center', justifyContent: 'center' }, pressed: { opacity: 0.6 }, disabled: { opacity: 0.35 }, divider: { height: StyleSheet.hairlineWidth }, emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.xl, gap: spacing.xs }, emptyTitle: { fontSize: 20, fontWeight: '600', textAlign: 'center' }, emptyDescription: { fontSize: 15, lineHeight: 22, textAlign: 'center' }, loadingScreen: { alignItems: 'center', justifyContent: 'center', gap: spacing.sm }, loadingText: { color: tokens.textSecondary, fontSize: 15 }, floatingSurface: { borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 4 }, bottomSheetSurface: { borderTopLeftRadius: 22, borderTopRightRadius: 22, borderWidth: StyleSheet.hairlineWidth }, primaryButton: { minHeight: layout.minimumTouchTarget, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.md }, primaryButtonText: { fontWeight: '700' }, secondaryButton: { minHeight: layout.minimumTouchTarget, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.md }, secondaryButtonText: { fontWeight: '600' }, destructiveAction: { minHeight: layout.minimumTouchTarget, justifyContent: 'center', paddingHorizontal: spacing.md }, destructiveText: { fontWeight: '700', textAlign: 'center' }, sectionHeader: { fontSize: 11, fontWeight: '700', letterSpacing: 0.8, marginTop: spacing.lg, marginBottom: spacing.xs }, listRow: { minHeight: 56, flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.xs, borderBottomWidth: StyleSheet.hairlineWidth }, listCopy: { flex: 1 }, listTitle: { fontSize: 16 }, listDetail: { fontSize: 13, marginTop: 3 }, toastWrap: { position: 'absolute', right: 0, bottom: 96, left: 0, alignItems: 'center' }, toast: { paddingHorizontal: spacing.md, paddingVertical: spacing.xs, borderRadius: 20, shadowColor: '#000', shadowOpacity: 0.16, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, elevation: 6 }, toastText: { fontSize: 14, fontWeight: '600' },
});
